version: "3.7"

services:
    db:
        image: "postgres:12"
        container_name: "postgres"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DATABASE: meetmeup_dev
        ports:
          - "5432:5432"
        volumes:
          - sql_db:/var/lib/postgresql/data
          - migrations:/migrations/
        networks:
          meetmeup:
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadminuser
            PGADMIN_DEFAULT_PASSWORD: "password"
        ports:
            - "5050:80"
        volumes:
            - "pgAdmin:/var/lib/pgadmin"
        networks:
            meetmeup:
volumes:
    sql_db:
    pgAdmin:
    migrations:
networks:
    meetmeup: